# Generated by Django 4.0.4 on 2022-04-13 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='create_date',
        ),
    ]
