# Generated by Django 4.0.4 on 2022-04-13 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_taskitem_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='todo_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskitems', to='app.todolist'),
        ),
    ]
